version: "3.9"

services:
  web:
    build:
      context: .
      args:
        DJANGO_ENV: production
    env_file: ./config/.env
    # command: gunicorn core.wsgi -b 0.0.0.0:8000
    command: sh ./gunicorn.sh
    environment: 
      - DJANGO_SETTINGS_MODULE=core.settings.production
    expose: 
      - 8000

  nginx:
    build: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
