version: "3.9"

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: ./config/.env

  web:
    build:
      context: .
      args:
        DJANGO_ENV: development
    volumes:
      - django-static:/var/www/django/static
    depends_on:
      - db
    env_file: ./config/.env
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment: 
      - DJANGO_SETTINGS_MODULE=core.settings.local

volumes:
  pgdata:
  django-static:
