version: "3.9"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    env_file: .env
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

volumes:
  pgdata:
