version: "3.9"
services:
  db:
    ports:
      - "5433:5432"
  web:
    ports:
      # We only bind ports directly in development:
      - "8000:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
