version: "3.9"

services:
  web:
    build:
      context: .
      args:
        DJANGO_ENV: production
    env_file: ./config/.env
    # command: gunicorn --env DJANGO_SETTINGS_MODULE=core.settings.production core.wsgi -b 0.0.0.0:8000
    command: sh ./gunicorn.sh
    ports:
      - "8000:8000" # test
