# Generated by Django 3.2.10 on 2021-12-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='quantity',
        ),
    ]
