# Generated by Django 3.2.10 on 2021-12-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_customer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
