# Generated by Django 3.2.10 on 2021-12-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='productType',
            field=models.CharField(choices=[('material', 'Material'), ('bathroom', 'Bathroom'), ('decorations', 'Decorations'), ('furniture', 'Furniture'), ('fabric_textile', 'Fabric Tex'), ('hardware_tool', 'Hardware Tool'), ('home_appliances', 'Home Appliances'), ('kitchen', 'Kitchen'), ('landscape_garden', 'Landscape'), ('light', 'Light'), ('rugs_mat', 'Rugs Mat'), ('security_protection', 'Sec Prot')], default='material', max_length=25),
        ),
    ]
