# Generated by Django 3.2.10 on 2021-12-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_producttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='productType',
            new_name='product_type',
        ),
    ]
