# Generated by Django 3.2.6 on 2021-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(max_length=128),
        ),
    ]
