# Generated by Django 3.2.10 on 2021-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_producttype_productimage_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomproducts',
            name='bathroom_product_type',
        ),
        migrations.RemoveField(
            model_name='decorationsproducts',
            name='decoration_product_type',
        ),
        migrations.RemoveField(
            model_name='fabrictextileproducts',
            name='fabrictextile_product_type',
        ),
        migrations.RemoveField(
            model_name='furnitureproducts',
            name='furniture_product_type',
        ),
        migrations.RemoveField(
            model_name='hardwaretoolproducts',
            name='hardwaretool_product_type',
        ),
        migrations.RemoveField(
            model_name='homeapplianceproducts',
            name='homeappliance_product_type',
        ),
        migrations.RemoveField(
            model_name='kitchenproducts',
            name='kitchen_product_type',
        ),
        migrations.RemoveField(
            model_name='landscapeproducts',
            name='landscape_product_type',
        ),
        migrations.RemoveField(
            model_name='lightproducts',
            name='light_product_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='rugsmatfloorproducts',
            name='rugmatfloor_product_type',
        ),
        migrations.RemoveField(
            model_name='securityprotectionproducts',
            name='securityprotection_product_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
