# Generated by Django 3.2.10 on 2021-12-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211215_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='decorationsproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='fabrictextileproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='furnitureproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='hardwaretoolproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='homeapplianceproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='kitchenproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='landscapeproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='lightproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='rugsmatfloorproducts',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='securityprotectionproducts',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
