# Generated by Django 3.2.6 on 2021-09-03 05:15

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='default_img.jpg', upload_to='products'),
        ),
    ]
