# Generated by Django 3.2.10 on 2021-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211215_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='decorationsproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='fabrictextileproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='furnitureproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='hardwaretoolproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='homeapplianceproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='kitchenproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='landscapeproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='lightproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='material',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='rugsmatfloorproducts',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='securityprotectionproducts',
            name='brand',
        ),
    ]
