# Generated by Django 3.2.10 on 2021-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('products', '0006_auto_20211223_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroomproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='decorationsproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='fabrictextileproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='furnitureproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='hardwaretoolproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='homeapplianceproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='kitchenproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='landscapeproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='lightproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='material',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='rugsmatfloorproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
        migrations.AddField(
            model_name='securityprotectionproducts',
            name='rooms',
            field=models.ManyToManyField(to='rooms.Room'),
        ),
    ]
