# Generated by Django 3.2.7 on 2021-09-27 12:16

from django.db import migrations
import products.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_uuid_null_20210903_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='default_img.jpg', upload_to=products.models.product_image_directory),
        ),
    ]
