# Generated by Django 3.2.7 on 2021-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
