# Generated by Django 3.2.7 on 2021-10-03 05:50

from django.db import migrations, models
import products.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_fields',
            field=models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text="dw it'll appear after you save the first time", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='default_img.jpg', max_length=600, upload_to=products.models.return_product_image_directory),
        ),
    ]
