# Generated by Django 3.2.7 on 2021-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211003_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True),
        ),
    ]
