# Generated by Django 3.2.7 on 2021-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            "DummyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        )
    ]
