# Generated by Django 3.2.7 on 2021-10-06 07:45

from django.db import migrations, models


def add_contenttype(apps, schema_editor):
    ProductImageModel = apps.get_model("products", "productimage")
    ContentType = apps.get_model("contenttypes", "ContentType")
    # use the temporary dummy model as contenttype instance
    ProductPatchContenttype = ContentType.objects.get(
        app_label="products", model="dummymodel"
    )

    for row in ProductImageModel.objects.all():
        # row.content_type = models.ForeignKey(
        #     ProductPatchContenttype, on_delete=models.CASCADE
        # )
        row.content_type = ProductPatchContenttype
        row.save(update_fields=["content_type"])


def add_object_id(apps, schema_editor):
    ProductImageModel = apps.get_model("products", "productimage")
    for row in ProductImageModel.objects.all():
        row.object_id = 1
        row.save(update_fields=["object_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_init_productimage_contenttype"),
    ]

    operations = [
        migrations.RunPython(add_contenttype, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_object_id, reverse_code=migrations.RunPython.noop),
    ]
