# Generated by Django 3.2.7 on 2021-10-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_populate_productImage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
