# Generated by Django 3.2.7 on 2021-10-06 12:20

from django.db import migrations, models
import django.db.models.deletion
import products.models.base
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0018_alter_productImage_nulltrue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='To add images, Add description images through the form below first and then insert the url of the image here')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('additional_fields', models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True)),
                ('place_of_origin', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('CHN', 'China')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('material_place', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('BOTH', 'Both')], max_length=15)),
                ('material_category', models.CharField(choices=[('WALL', 'Wall material'), ('CEILING', 'Ceiling material'), ('FLOOR', 'Floor material')], max_length=7)),
                ('thickness', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('density', models.CharField(blank=True, max_length=50)),
                ('brand', models.ManyToManyField(related_name='brands', related_query_name='brand', to='products.Brand')),
            ],
            options={
                'ordering': ['updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'products'), ('model', 'material')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(max_length=600, upload_to=products.models.base.return_product_image_directory),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ManyToManyField(related_name='material_types', related_query_name='material_type', to='products.Category'),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ManyToManyField(related_name='suppliers', related_query_name='supplier', to='products.Supplier'),
        ),
    ]
