# Generated by Django 3.2.7 on 2021-10-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20211006_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
