# Generated by Django 3.2.7 on 2021-10-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_dummymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Finish Material', 'verbose_name_plural': 'Finish Materials'},
        ),
    ]
