# Generated by Django 3.2.7 on 2021-10-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='brand',
            field=models.ManyToManyField(related_name='products_material_related', related_query_name='products_materials', to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ManyToManyField(related_name='products_material_related', related_query_name='products_materials', to='products.Supplier'),
        ),
    ]
