# Generated by Django 3.2.7 on 2021-10-09 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20211009_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProtectionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='To add images, Add description images through the form below first and then insert the url of the image here')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('additional_fields', models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True)),
                ('place_of_origin', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('CHN', 'China')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_securityprotectionproducts_related', related_query_name='products_securityprotectionproductss', to='products.brand')),
                ('securityprotection_product_type', models.ManyToManyField(related_name='securityprotection_product_types', related_query_name='securityprotection_product_type', to='products.Category')),
                ('supplier', models.ManyToManyField(blank=True, related_name='products_securityprotectionproducts_related', related_query_name='products_securityprotectionproductss', to='products.Supplier')),
            ],
            options={
                'verbose_name': 'Security and Protection Product',
                'verbose_name_plural': 'Security and Protection Products',
            },
        ),
        migrations.CreateModel(
            name='RugsMatFloorProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='To add images, Add description images through the form below first and then insert the url of the image here')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('additional_fields', models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True)),
                ('place_of_origin', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('CHN', 'China')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_rugsmatfloorproducts_related', related_query_name='products_rugsmatfloorproductss', to='products.brand')),
                ('rugmatfloor_product_type', models.ManyToManyField(related_name='rugmatfloor_product_types', related_query_name='rugmatfloor_product_type', to='products.Category')),
                ('supplier', models.ManyToManyField(blank=True, related_name='products_rugsmatfloorproducts_related', related_query_name='products_rugsmatfloorproductss', to='products.Supplier')),
            ],
            options={
                'verbose_name': 'Rugs Mats and Floor Product',
                'verbose_name_plural': 'Rugs Mats and Floor Products',
            },
        ),
        migrations.CreateModel(
            name='LightProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='To add images, Add description images through the form below first and then insert the url of the image here')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('additional_fields', models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True)),
                ('place_of_origin', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('CHN', 'China')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_lightproducts_related', related_query_name='products_lightproductss', to='products.brand')),
                ('light_product_type', models.ManyToManyField(related_name='light_product_types', related_query_name='light_product_type', to='products.Category')),
                ('supplier', models.ManyToManyField(blank=True, related_name='products_lightproducts_related', related_query_name='products_lightproductss', to='products.Supplier')),
            ],
            options={
                'verbose_name': 'Light Product',
                'verbose_name_plural': 'Light Products',
            },
        ),
        migrations.CreateModel(
            name='LandscapeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('slug', models.SlugField(help_text='URL, will appear after you save for the first time', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='To add images, Add description images through the form below first and then insert the url of the image here')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('additional_fields', models.JSONField(blank=True, help_text="To add extra fields, you can write a json. Delete the 'null' and start writing!", null=True)),
                ('place_of_origin', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('CHN', 'China')], max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_landscapeproducts_related', related_query_name='products_landscapeproductss', to='products.brand')),
                ('landscape_product_type', models.ManyToManyField(related_name='landscape_product_types', related_query_name='landscape_product_type', to='products.Category')),
                ('supplier', models.ManyToManyField(blank=True, related_name='products_landscapeproducts_related', related_query_name='products_landscapeproductss', to='products.Supplier')),
            ],
            options={
                'verbose_name': 'Landscape and Garden Product',
                'verbose_name_plural': 'Landscape and Garden Products',
            },
        ),
    ]
